import = ["/Users/j.vos/.config/alacritty/themes/themes/monokai_charcoal.toml"]

live_config_reload = true
[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[font]
size = 18.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false

