import = ["/Users/j.vos/.config/alacritty/themes/themes/monokai_charcoal.toml"]

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"
