#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `find . -regex ".*\.vim"`; do
    fs="${f:2}"
    echo $fs
    rm -rf ~/.config/nvim/$fs
    ln -s /Users/vosjoppe/vos-dotfiles/$fs /Users/vosjoppe/.config/nvim/$fs
done

