---
# config file for pre-commit python
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        files: \.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812  
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs, --ignore-missing-imports]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        files: \.py$
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        name: Run isort to sort imports
        description: "Sorts python imports"
        files: \.py$
